### PR TITLE
fix: obsidian syntax for embedded images

### PR DESCRIPTION
**Pull request by joncotton**
First thing, thank you for Yarle. It's excellent and much appreciated.

Second, a small touch up per https://help.obsidian.md/How+to/Embed+files#Resize+images

> You can resize images using the following syntax:
> For markdown images, use `AltText|100x100`
> For embeds, use `![[image.png|100x100]]`

### CODE REVIEW

**Comment by joncotton** [comment]
The first commit stands alone. The second addresses another behavior I found with 0x0 images.

Some resulting markdown has `0x0` image sizes, meaning the image is there but not visible. I'm not sure if the source ENEX file element is an `<en-media>` without width and height attributes (it seems to have and maybe the attrs are lost earlier in the processing chain). Either way, the best choice seems to be that if _both_ width and height attributes are empty strings, don't set the syntax for image sizing at all.

**Comment by akosbalasko** [comment]
Hi @joncotton , 
Thanks for the PR, looks pretty good, I've got two short comments only: 
I think it's just valid for Obsidian only, so if it's true, please extend the condition by checking the target format that has to be ObsidianMD. 
Then, could you please add some unit tests to keep the coverage? 
Thanks a lot!

**Comment by joncotton** [comment]
Hi. I think the Obsidian check is accounted for by the parent logic, which is unchanged. I'll examine again when adding tests. Which I intended to do this week but raked so many leaves instead. 🍃

**Comment by joaosa** [comment]
I could use this as well 👍

**Review by akosbalasko — APPROVED** [review]

**Pull request merged**
