### PR TITLE
Add option to make use of hashtags configurable

### PR DESCRIPTION
**Pull request by Cito**
For instance, in the Obsidian frontmatter you don't want hashtags. If you use tags outside the frontmatter in Obsidian, you have to use hashtags. So I made this setting independent of the outputFormat. The default is true, so this is fully backward compatible.

### CODE REVIEW

**Comment by nununo** [comment]
Hi,
This still doesn't seem to be working for me. I'm using the no-install command provided in the REAME so I assume I'm running the latest version which `npm search` reports as being `3.2.3`.

My `config.json` is:

```json
{
    "enexSource": "/enex/cozinhado.enex",
    "templateFile": "../../../../../Documents/obsidian/evernote/template.md",
    "outputDir": "out",
    "isMetadataNeeded": true,
    "isNotebookNameNeeded": true,
    "isZettelkastenNeeded": false,
    "plainTextNotesOnly": false,
    "skipLocation": false,
    "skipCreationTime": false,
    "skipUpdateTime": false,
    "skipWebClips": false,
    "skipTags": false,
    "useHashTags": false,
    "outputFormat": "ObsidianMD",
    "skipEnexFileNameFromOutputPath": false
}
```

And it generates the files. But the tags are still hashed.

Am I doing something wrong?

Thanks,
Nuno

**Comment by Cito** [comment]
What does `npm view yarle-evernote-to-md version` show?

**Comment by nununo** [comment]
> What does `npm view yarle-evernote-to-md version` show?

`3.2.3`

**Comment by Cito** [comment]
And are you sure that this config is being used? Try renaming the outputDir to "out2" in look what's produced there.

**Comment by nununo** [comment]
I'm sure :) I just did what you suggested and the conversion was made into a newly generated `out2` folder.

This template:
```text
---
{tags-block}tags: {tags}{end-tags-block}
---
```

Generates this:

```md
---
tags: #15min #5x #sobremesa
---
```

**Comment by Cito** [comment]
I was asking because it works perfectly fine for me, using npx with 3.2.3. And when I toggle the flag in the config file, I see the hashtags appear and disappear in the result.

**Comment by nununo** [comment]
Damn.

Could it be due to interdependencies with other config flags?
Are you running an installed version or the no-install `npx` command? No idea if this makes any difference.

I'm anxious to make this work because, once it works, I can finally import the missing Evernote notebooks and ditch it once and for all 😄

**Comment by Cito** [comment]
I tried both, and both works. Also, looking at the code, there should be no influence from other flags. I guess the problem is you're still using an old version of the package. And I think `npm view` and `npm search` show only what's in the repository, not what is installed. Can you try this? `npm list --depth=0`

**Comment by Cito** [comment]
Just checked the docs, and yes, `npm search` and `npm view` show only what's in the registry. It may be that you have still installed an older version and npx is using this. If the trick with `@latest` helps you, we should add this in the README.

**Comment by Cito** [comment]
Btw, I'm still waiting for #127, #128 and most importantly #81 before I will ditch my old notebooks.

**Comment by nununo** [comment]
Hi @Cito, I am not familiar with how `npm` works. This is what I get:
```bash
% npm list --depth=0
/Users/myuser
└── (empty)
```

Is this what's expected? Must I run this command in a specific folder?

I have installed `yarle`'s previous version but I explicitly uninstalled and confirmed that the binary disappeared before running this latest one. Yet, I don't really know how `npm` does its thing.

**Comment by nununo** [comment]
Wait! I hadn't noticed your suggestion of using `@latest`! That did the trick! It warned me that it needed to install a new version, downloaded it and... no more hashes!!! THANK YOU!

I was indeed still running an old version. My bad. Sorry for wasting your time. I really must learn how this `npm` thing works.

**Comment by Cito** [comment]
Thanks for the feedback. Sorry, I forgot the `-g` switch when I first posted the `npm list` command. This should show you the globally installed package version. Without the `-g` you see only the local installation in the current folder.

Will create a PR for adding the `@latest` to the README. I don't think this is obvious.

**Comment by nununo** [comment]
> Btw, I'm still waiting for #127, #128 and most importantly #81 before I will ditch my old notebooks.

I agree with you. @akosbalasko is being so amazing at developing this tool (thanks 😄) that it's probably worth waiting a little more for #127 and #128. Not so much for #81 as much as I totally understand why you want it.

**Comment by nununo** [comment]
`-g`. Got it. Thanks!

**Pull request merged**
