### PR TITLE
feat: external link rule extended by <url>

### PR DESCRIPTION
**Pull request by akosbalasko**
closes: https://github.com/akosbalasko/yarle/issues/133

### CODE REVIEW

**Comment by nununo** [comment]
Hi,

I found that this scenario is still not taken into consideration:

```markdown
[https://food52.com/blog/21133-smitten-kitchen-farro-salad-slaw-genius?utm\_campaign=activity\_feed&utm\_medium=email&utm\_source=food52](https://food52.com/blog/21133-smitten-kitchen-farro-salad-slaw-genius?utm_campaign=activity_feed&amp;utm_medium=email&amp;utm_source=food52)
```

Because some characters in the first url are escaped (in this case all the `_` are escaped to `\_`) and as a result the first url is not equal to the second one and thus it is not rendered in the simplified form.

Regards,
Nuno

**Comment by akosbalasko** [comment]
Hi @nununo ,

did you set the config to do not escape md characters?  ```keepMDCharactersOfENNotes``` should be set to true.

**Comment by nununo** [comment]
Hi @akosbalasko,

You're quick 👍 

Sorry, I hadn't noticed that new flag. That's great. Yet, it still doesn't work for a different reason: the url is still escaping some characters, like the &.

Here's the rendered url with `keepMDCharactersOfENNotes: true`:
```markdown
[https://food52.com/blog/8524-alon-shaya-s-whole-roasted-cauliflower-with-whipped-goat-cheese?utm\_source=Facebook&utm\_medium=SocialMarketing&utm\_campaign=Genius](https://food52.com/blog/8524-alon-shaya-s-whole-roasted-cauliflower-with-whipped-goat-cheese?utm_source=Facebook&amp;utm_medium=SocialMarketing&amp;utm_campaign=Genius)
```

And this is what I get for the same url with `keepMDCharactersOfENNotes: false`:
```markdown
[https://food52.com/blog/8524-alon-shaya-s-whole-roasted-cauliflower-with-whipped-goat-cheese?utm_source=Facebook&utm_medium=SocialMarketing&utm_campaign=Genius](https://food52.com/blog/8524-alon-shaya-s-whole-roasted-cauliflower-with-whipped-goat-cheese?utm_source=Facebook&amp;utm_medium=SocialMarketing&amp;utm_campaign=Genius)
```

I hope this helps! Thank you!

Cheers,
Nuno

**Comment by akosbalasko** [comment]
Oh, okay, sorry. I tried to reproduce the issue, without success. Nevertheless, I had an idea about the fix, so I implemented that and released a new version (3.4.2). Please give it a try, hope it will work for you too.

**Comment by nununo** [comment]
@akosbalasko it worked! Perfect! Thanks!!

This was the only missing thing for me. I'm now ready to import all my stuff from Evernote. Thanks you again!!

**Pull request merged**
