### PR TITLE
feat: add `turndownOptions` config option

### PR DESCRIPTION
**Pull request by medmunds**
Allow configuration of additional Turndown options.
E.g., to use atx-style headings (`## Heading2` rather than
`Heading2\n--------`), in the Yarle config file set:

```json
{
  "...otherConfig": "...",
  "turndownOptions": { "headingStyle": "atx" }
}
```

(This PR does not expose the new option in the Electron UI.)

### CODE REVIEW

**Review by akosbalasko — CHANGES_REQUESTED** [review]
Wow, it's amazing, thank you for adding this option I did not even think about it. 
One short request: could you please extend the Readme by adding that this option is currently cannot be used from the UI?
Thank you very much!

**Comment by medmunds** [comment]
Readme updated.

BTW, I wonder if it might make sense to change the default headingStyle to atx? (Joplin's built-in converter seems to always use atx. The underline-style headings are a hassle to use without editor support.)

**Comment by akosbalasko** [comment]
Sure, sure, the default options are stored by ```defaultYarleOptions``` variable in yarle.ts in the root src folder, feel free to set this option as atx. 

Thanks a lot!

**Comment by medmunds** [comment]
If you're planning to merge this PR, I'll submit a separate one to change the `defaultYarleOptions` after.

**Comment by akosbalasko** [comment]
Pls add it here, I'd add the UI for the resourceDir, so I'd merge that PR before this. You're fast :)

**Comment by medmunds** [comment]
OK, changed the default heading style. (And rebased to main branch.)

Since lodash is already available, I switched the options init to just use its deep `merge()` for simplicity.

**Review by akosbalasko — APPROVED** [review]

**Review by akosbalasko — APPROVED** [review]

**Pull request merged**
